apiVersion: v1
kind: Service
metadata:
  labels:
    app: papermc
  name: metrics
  namespace: minecraft
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 12345
    protocol: TCP
    targetPort: 12345
  selector:
    app: papermc
  sessionAffinity: None
  type: ClusterIP
