apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: papermc
  namespace: minecraft
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app: papermc
