apiVersion: v1
items:
- apiVersion: v1
  data:
    forwarding.secret:
  kind: Secret
  metadata:
    name: velocity-forwarding
    namespace: minecraft
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
