apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: papermc
    namespace: minecraft
  spec:
    endpoints:
    - interval: 30s
      port: metrics
      scheme: http
    selector:
      matchLabels:
        app: papermc
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: velocity
    namespace: minecraft
  spec:
    endpoints:
    - interval: 30s
      port: metrics
      scheme: http
    selector:
      matchLabels:
        app: velocity
kind: List
metadata:
  resourceVersion: ""
